// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBjDTSyJlUALLkCDwWK7r5TMSKhh0XyW0',
    appId: '1:277535198725:web:73de9e361ab3734a07166c',
    messagingSenderId: '277535198725',
    projectId: 'rigging-c0661',
    authDomain: 'rigging-c0661.firebaseapp.com',
    databaseURL:
        'https://rigging-c0661-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rigging-c0661.appspot.com',
    measurementId: 'G-HDKJ4X7B84',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBjDTSyJlUALLkCDwWK7r5TMSKhh0XyW0',
    appId: '1:277535198725:web:5814a9da0133129907166c',
    messagingSenderId: '277535198725',
    projectId: 'rigging-c0661',
    authDomain: 'rigging-c0661.firebaseapp.com',
    databaseURL:
        'https://rigging-c0661-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rigging-c0661.appspot.com',
    measurementId: 'G-L6V1MNG108',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfEJ1Z2OYw299bIWWqR0Hncmd-HiCHIFc',
    appId: '1:277535198725:ios:2b1cfcda030ef79c07166c',
    messagingSenderId: '277535198725',
    projectId: 'rigging-c0661',
    databaseURL:
        'https://rigging-c0661-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rigging-c0661.appspot.com',
    iosBundleId: 'com.rigging_quiz.rigging_quiz',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfEJ1Z2OYw299bIWWqR0Hncmd-HiCHIFc',
    appId: '1:277535198725:ios:2b1cfcda030ef79c07166c',
    messagingSenderId: '277535198725',
    projectId: 'rigging-c0661',
    databaseURL:
        'https://rigging-c0661-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rigging-c0661.appspot.com',
    iosBundleId: 'com.rigging_quiz.rigging_quiz',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhEepXtc-PFnV_QFqdAp0O33fkPDq_CEI',
    appId: '1:277535198725:android:272f8466ce7d471107166c',
    messagingSenderId: '277535198725',
    projectId: 'rigging-c0661',
    databaseURL:
        'https://rigging-c0661-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rigging-c0661.appspot.com',
  );
}
